# Exemplo de arquivo docker-compose.yml
# Altere todos os valores que estão com # para os valores do seu projeto
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: DB_USER # Altere o usuário do banco de dados
      POSTGRES_PASSWORD: DB_PASS # Altere a senha do banco de dados
      POSTGRES_DB: DB_NAME # Altere o nome do banco de dados
    ports:
      - "PORT:5432" # Altere a porta para a porta que deseja expor
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - application-network

  api:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - DOMAIN= # Domínio da aplicação
      - KOMMO_AUTH= # Token de acesso do Kommo
      - KOMMO_URL= # URL do Kommo
      - DB_URL=postgres://DB_USER:DB_PASS@database:5432/DB_NAME # URL de conexão com o banco de dados (postgres://DB_USER:DB_PASS@DB_HOST:DB_PORT/DB_NAME)
      - TZ=America/Sao_Paulo
      - OPENAI_API_KEY= # Chave de API do OpenAI
      - OPENAI_ASSISTANT_ID= # ID do assistente do OpenAI
      - EVOLUTION_API_BASE_URL= # URL base da API do Evolution API
      - EVOLUTION_API_INSTANCE_ID= # ID da instância da API do Evolution API
      - EVOLUTION_API_KEY= # Chave de API do Evolution API
      - WHATSAPP_NUMBER=558130930133 # Número do WhatsApp
    expose:
      - "PORT" # Altere para a porta que deseja expor
    ports:
      - "PORT:3000" # Altere para a porta que deseja expor
    networks:
      - application-network

volumes:
  data:

networks:
  application-network:
    external: true
