services:
  dental_sante_backend:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - DB_URL=postgres://DB_USER:DB_PASS@DB_HOST:DB_PORT/DB_NAME # Altere os valores para os valores do seu banco de dados
    expose:
      - "PORT" # Altere para a porta que deseja expor
    ports:
      - "PORT:3000" # Altere para a porta que deseja expor