services:
  dental_sante_database:
    image: postgres:16
    environment:
      POSTGRES_USER: DB_USER # Altere o usuário do banco de dados
      POSTGRES_PASSWORD: DB_PASS # Altere a senha do banco de dados
      POSTGRES_DB: DB_NAME # Altere o nome do banco de dados
    ports:
      - "PORT:5432" # Altere a porta para a porta que deseja expor
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - dental-sante-network

  dental_sante_backend:
    depends_on:
      - dental_sante_database
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - TABLE_NAME=lead_threads # Altere o nome da tabela
      - DB_URL=postgres://DB_USER:DB_PASS@DB_HOST:DB_PORT/DB_NAME # Altere as informações de conexão com o banco de dados
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - dental-sante-network

volumes:
  data:

networks:
  dental-sante-network:
    external: true
