services:
  backend:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DIALECT=postgres
      - DB_HOST=aiatende.com
      - DB_NAME=lead-conversation
      - TABLE_NAME=lead_threads
      - DB_URL=postgres://docker:docker@aiatende.com:5432/lead-conversation
    expose:
      - "3005"
    ports:
      - "3005:3005"
    networks:
      - app-network

  nginx:
    restart: always
    build: ./nginx
    ports:
        - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
