version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lead-conversation
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ai-atende-network

  backend:
    depends_on:
      - database
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - DB_NAME=lead-conversation
      - TABLE_NAME=lead_threads
      - DB_URL=postgres://docker:docker@database:5432/lead-conversation
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - ai-atende-network

volumes:
  data:

networks:
  ai-atende-network:
    external: true