services:
  dental_sante_backend:
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - DB_URL=postgres://docker:docker@server.aiatende.dev.br:4000/lead-conversation
    expose:
      - "3000"
    ports:
      - "3000:3000"