services:
  cl001-nelson-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker_nelson
      POSTGRES_PASSWORD: docker_nelson
      POSTGRES_DB: lead-conversation
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - cl001-nelson-ntwrk

  cl001-nelson-backend:
    depends_on:
      - cl001-nelson-db
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DIALECT=postgres
      - DB_HOST=cl001-nelson-db
      - DB_NAME=lead-conversation
      - DB_PORT=5432
      - TABLE_NAME=lead_threads
      - DB_URL=postgres://docker:docker@database:5432/lead-conversation
    expose:
      - "3100"
    ports:
      - "3100:3100"
    networks:
      - cl001-nelson-ntwrk
    
  cl001-nelson-nginx:
    restart: always
    build: ./nginx
    ports:
        - "4000:4000"
    depends_on:
      - cl001-nelson-backend
    networks:
      - cl001-nelson-ntwrk

volumes:
  data:

networks:
  cl001-nelson-ntwrk:
    external: true