version: '3'
services:
  node-app:
    build: ./node-app
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DIALECT=postgres
      - DB_HOST=aiatende.com
      - DB_NAME=lead-conversation
      - TABLE_NAME=lead_threads
      - DB_URL=postgres://docker:docker@aiatende.com:5432/lead-conversation
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app-network
  nginx:
    restart: always
    build: ./nginx
    ports:
        - "8081:8080"
    depends_on:
      - node-app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
