services:
  cl001-nelson-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lead-conversation
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ai-atende-network

  cl001-nelson-backend:
    depends_on:
      - cl001-nelson-db
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - DB_NAME=lead-conversation
      - TABLE_NAME=lead_threads
      - DB_URL=postgres://docker:docker@database:5433/lead-conversation
    expose:
      - "3100"
    ports:
      - "3100:3100"
    networks:
      - ai-atende-network
    
  cl001-nelson-nginx:
    restart: always
    build: ./nginx
    ports:
        - "4000:4000"
    depends_on:
      - cl001-nelson-backend
    networks:
      - ai-atende-network

volumes:
  data:

networks:
  ai-atende-network:
    external: true